image: "ruby:2.7"


before_script:
  - ruby -v  # Print out ruby version for debugging
  - bundle install
  - gem install rspec
  - mkdir ~/.gem || true
  - touch ~/.gem/credentials || true
  - url_host=`git remote get-url origin | sed -e "s/https:\/\/gitlab-ci-token:.*@//g"`
    # runner runs on a detached HEAD, checkout current branch for editing
  - git reset --hard
  - git clean -fd
  - git checkout $CI_COMMIT_REF_NAME
  - git pull origin $CI_COMMIT_REF_NAME
  - |-
     echo "---
     :rubygems_api_key: $RUBYGEM_KEY" > ~/.gem/credentials

rspec:
  stage: test
  script:
    - rspec spec

build:
  stage: build
  script:
    - rake build

prepare_deployment:
  stage: deploy
  only:
    - web
  script:
    - rake spec
    - rake build
    - git config --global user.email "sebastian@sebsoft.nl"
    - git config --global user.name "Sebastian Berm"
    - git remote set-url origin "https://$GIT_ACCESS_USER:$GIT_ACCESS_PASSWORD@${url_host}"
    - rake release
